In [1]:
# lectura de los datos

import pandas as pd
import read_data

# Suponiendo que el activo tiene ese nombre
# solo es remplazar por el nombre que se tenga
# solo se acepta archivos .parquet y .csv
nombre_activo: str = "EURUSD_2019-2025.parquet"
data: pd.DataFrame = pd.read_parquet(f"Data/{nombre_activo}")

primer_lunes = data[data.index.dayofweek == 0].index[0]
ultimo_viernes = data[data.index.dayofweek == 4].index[-1]

data = data.loc[primer_lunes: ultimo_viernes]
data = data.between_time('07:00', '16:00')
data

                     Precio Spot
time
2019-01-07 07:00:00     1.142020
2019-01-07 07:01:00     1.142060
2019-01-07 07:02:00     1.142060
2019-01-07 07:03:00     1.142180
2019-01-07 07:04:00     1.142170
...                          ...
2026-02-13 15:56:00     1.187810
2026-02-13 15:57:00     1.187695
2026-02-13 15:58:00     1.187485
2026-02-13 15:59:00     1.187420
2026-02-13 16:00:00     1.187060

[1052237 rows x 1 columns]

In [2]:
import numpy as np
import pandas as pd

ma_week = []

with open("Data/Moving_average_test.txt", "r") as archivo:

    for line in archivo:
        start = pd.Timestamp(line[:10])
        fin = pd.Timestamp(line[11:21])

        lista = eval(line[22: ], {"np": np})

        ma_week.append([start, fin, lista])

In [15]:
import train_network

X, y = train_network.build_weekly_dataset(data, ma_week)

In [16]:
import train_network

model = train_network.train_model(X, y)

Reporte de Clasificación (Test Set):
              precision    recall  f1-score   support

           0       0.58      0.43      0.49      2336
           1       0.64      0.77      0.70      3119

    accuracy                           0.62      5455
   macro avg       0.61      0.60      0.60      5455
weighted avg       0.62      0.62      0.61      5455


Importancia de las Features:
raw_volatility             0.275666
volatility_regime_ratio    0.162882
trend_context_ratio        0.150493
momentum_rsi               0.149998
curvature                  0.144781
range_location_wr          0.116180
dtype: float64

In [20]:
import joblib

nombre_archivo = "modelo_filtro_ma.joblib"
joblib.dump(model, nombre_archivo)

print(f"¡Modelo guardado exitosamente como {nombre_archivo}!")

¡Modelo guardado exitosamente como modelo_filtro_ma.joblib!

In [5]:
import joblib

model = joblib.load("modelo_filtro_ma.joblib")

In [19]:
from tester import backtest
from use_tecnics import main

def get_info_in_week(data: pd.DataFrame, week: list) -> pd.DataFrame:
    time_col = week[0] - pd.Timedelta(weeks=1)

    data_week_raw = data.loc[time_col: week[1]]

    velas_cerradas = read_data.ohlc_form(
        data_week_raw,
        f"{week[2][1]}min"
    )["close"]

    method_name = week[2][0]
    params = week[2][2]

    df_week = main(method_name, velas_cerradas, params)

    df_week = df_week.loc[week[0]: week[1]]

    if len(df_week) == 0:
        return pd.DataFrame()

    return df_week

def get_signals_and_prices(data: pd.DataFrame, ma_week: list) -> pd.DataFrame:
    signals_and_prices = []

    for week in ma_week:
        data_week = get_info_in_week(data, week)

        if len(data_week) == 0:
            continue

        if len(data_week) > 1:
            f_i = data_week.index[0]
            l_i = data_week.index[-1]

            if data_week["Signals"][f_i] == -1:
                f_i = data_week.index[1]

            if data_week["Signals"][l_i] == 1:
                l_i = data_week.index[-2]

            data_week = data_week.loc[f_i: l_i]
        
        signals_and_prices.append(data_week)

    if len(signals_and_prices) == 0:
        return pd.DataFrame()

    signals_and_prices = pd.concat(signals_and_prices)

    signals_and_prices = signals_and_prices.sort_index()
    signals_and_prices = signals_and_prices[~signals_and_prices.index.duplicated()]

    return signals_and_prices

signals_and_prices_c = get_signals_and_prices(data, ma_week[-4:-3])
backtest(signals_and_prices_c)

(np.float64(0.8888888888888888),
 np.float64(1.319999999999826),
 np.float64(10.559999999998608),
 9)

In [27]:
signals_and_prices_c

                     Signals   Prices
time
2019-11-04 21:20:00        1  1.11552
2019-11-06 11:40:00       -1  1.10914
2019-11-06 12:00:00        1  1.10894
2019-11-06 14:40:00       -1  1.10896
2019-11-06 15:40:00        1  1.10879
2019-11-06 22:20:00       -1  1.10870
2019-11-07 07:00:00        1  1.10594
2019-11-07 10:40:00       -1  1.10831
2019-11-07 11:20:00        1  1.10766
2019-11-07 12:00:00       -1  1.10831
2019-11-07 13:40:00        1  1.10795
2019-11-07 14:00:00       -1  1.10818
2019-11-07 14:20:00        1  1.10745
2019-11-07 15:00:00       -1  1.10805

In [6]:
from train_network import filter_signals_with_ml

signals_and_prices = filter_signals_with_ml(data, ma_week[-48:], model, umbral=.6)

In [14]:
backtest(signals_and_prices)

(np.float64(0.7494866529774127),
 np.float64(0.38063756080173566),
 np.float64(1.1874590572019958),
 487)

In [13]:
#signals_and_prices = signals_and_prices.loc[signals_and_prices["Signals"] != 0]
signals_and_prices = signals_and_prices.loc[signals_and_prices["Signals"] != signals_and_prices["Signals"].shift(1)]
signals_and_prices

                     Signals   Prices
time
2025-03-24 08:02:00        1  1.08196
2025-03-24 08:13:00       -1  1.08221
2025-03-25 14:50:00        1  1.08185
2025-03-25 15:01:00       -1  1.08216
2025-03-25 15:12:00        1  1.08164
...                      ...      ...
2026-02-12 15:30:00       -1  1.18827
2026-02-13 11:50:00        1  1.18607
2026-02-13 13:10:00       -1  1.18597
2026-02-13 13:20:00        1  1.18584
2026-02-13 13:50:00       -1  1.18588

[974 rows x 2 columns]

In [20]:
import pandas as pd
import matplotlib.pyplot as plt

def simular_trading_basico(señales_precios, capital_inicial=1000.0, valor_pip=0.4*0.000):
    compradas = 0
    capital_operativo = capital_inicial

    pico_maximo = capital_inicial
    max_drawdown = 0.0
    
    for idx in señales_precios.index:
        precio_actual = señales_precios["Prices"][idx]
        senal = señales_precios["Signals"][idx]

        if senal == 1:
            precio_compra = precio_actual + valor_pip
            if capital_operativo >= precio_compra:
                nuevas_compras = int(capital_operativo / precio_compra)
                compradas += nuevas_compras
                capital_operativo -= nuevas_compras * precio_compra

        elif senal == -1: 
            precio_venta = precio_actual - valor_pip
            capital_operativo += compradas * precio_venta
            compradas = 0
                
        patrimonio_actual = capital_operativo + (compradas * precio_actual)

        if patrimonio_actual > pico_maximo:
            pico_maximo = patrimonio_actual
            
        drawdown_actual = (pico_maximo - patrimonio_actual) / pico_maximo
        
        if drawdown_actual > max_drawdown:
            max_drawdown = drawdown_actual

    print(f"--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---")
    print(f"Patrimonio Total Final: ${patrimonio_actual:.2f}")
    print(f"Capital Inicial: ${capital_inicial:.2f}")
    print(f"Beneficio Neto: ${(patrimonio_actual - capital_inicial):.2f}")
    print(f"Max Drawdown: {max_drawdown * 100:.2f}%\n")
    
    return patrimonio_actual, max_drawdown

simular_trading_basico(signals_and_prices_c)
simular_trading_basico(signals_and_prices)
print("")

--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---
Patrimonio Total Final: $1005.04
Capital Inicial: $1000.00
Beneficio Neto: $5.04
Max Drawdown: 0.05%

--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---
Patrimonio Total Final: $1032.51
Capital Inicial: $1000.00
Beneficio Neto: $32.51
Max Drawdown: 2.54%

In [2]:


import pandas as pd
import find_best
import keys
from use_tecnics import simple_methods

keys.methods = simple_methods
keys.candles = 20
keys.calls = 15

dias_comp_sem = pd.Timedelta(days=4)
next_lun = pd.Timedelta(days=3)
ventana_ent = pd.Timedelta(weeks=3) + dias_comp_sem

primer_lunes = data[data.index.dayofweek == 0].index[0]
ultimo_viernes = data[data.index.dayofweek == 4].index[-1]

inicio_actual = primer_lunes

with open("Data/Moving_average_test.txt", "w") as archivo:
    archivo.write("") 

while True:
    train_time_init = inicio_actual
    train_time_fin = inicio_actual + ventana_ent

    test_time_init = train_time_fin + next_lun
    test_time_fin = test_time_init + dias_comp_sem

    if train_time_fin >= ultimo_viernes:
        break

    print(f"Optimizando ventana: {train_time_init.date()} al {train_time_fin.date()}")

    data_w = data.loc[train_time_init : train_time_fin]
    
    if len(data_w) < 100:
        inicio_actual += (dias_comp_sem + next_lun)
        continue

    best_ma = find_best.opti_main(data_w)

    with open("Data/Moving_average_test.txt", "a") as archivo:
        archivo.write(f"{test_time_init.date()} {test_time_fin.date()}, {best_ma}\n")

    inicio_actual += (dias_comp_sem + next_lun)

Optimizando ventana: 2019-01-07 al 2019-02-01
Resultado obtenido entrenando desde 2019-01-07 hasta 2019-02-01
Método: TRIMA, Datos optimizados [np.int64(19), np.int64(82)]

hit ratio: 0.7931034482758621
risk reward: 0.44826201674888455
profit factor: 3.436675461741449
trades: 29
Resultado de sobre ajuste 0.5951065052145034
Optimizando ventana: 2019-01-14 al 2019-02-08
Resultado obtenido entrenando desde 2019-01-14 hasta 2019-02-08
Método: MIDPOINT, Datos optimizados [np.int64(14), np.int64(92)]

hit ratio: 0.7741935483870968
risk reward: 0.40576983380368836
profit factor: 2.43461900282213
trades: 31
Resultado de sobre ajuste 0.9365959815069452
Optimizando ventana: 2019-01-21 al 2019-02-15
Resultado obtenido entrenando desde 2019-01-21 hasta 2019-02-15
Método: SMA, Datos optimizados [np.int64(14), np.int64(78)]

hit ratio: 0.7777777777777778
risk reward: 0.4223487356017568
profit factor: 2.9564411492122975
trades: 27
Resultado de sobre ajuste 0.8333299708032696
Optimizando ventana: 2019-01-28 al 2019-02-22
Resultado obtenido entrenando desde 2019-01-28 hasta 2019-02-22
Método: KAMA, Datos optimizados [np.int64(19), np.int64(79)]

hit ratio: 0.8529411764705882
risk reward: 0.48309850451119085
profit factor: 2.8019713261649075
trades: 34
Resultado de sobre ajuste 1.6544667747918977
Optimizando ventana: 2019-02-04 al 2019-03-01
Resultado obtenido entrenando desde 2019-02-04 hasta 2019-03-01
Método: MIDPOINT, Datos optimizados [np.int64(8), np.int64(29)]

hit ratio: 0.6705882352941176
risk reward: 0.6279491833031017
profit factor: 1.9885057471264884
trades: 85
Resultado de sobre ajuste 0.0049855450688713965
Optimizando ventana: 2019-02-11 al 2019-03-08
Resultado obtenido entrenando desde 2019-02-11 hasta 2019-03-08
Método: KAMA, Datos optimizados [np.int64(18), np.int64(78)]

hit ratio: 0.896551724137931
risk reward: 0.4167216903268229
profit factor: 3.611587982832465
trades: 29
Resultado de sobre ajuste 1.4181383830350704
Optimizando ventana: 2019-02-18 al 2019-03-15
Resultado obtenido entrenando desde 2019-02-18 hasta 2019-03-15
Método: T3, Datos optimizados [np.int64(9), np.int64(84)]

hit ratio: 0.8529411764705882
risk reward: 0.27680128807193544
profit factor: 2.0068093385215318
trades: 34
Resultado de sobre ajuste -0.008667179440892762
Optimizando ventana: 2019-02-25 al 2019-03-22
Resultado obtenido entrenando desde 2019-02-25 hasta 2019-03-22
Método: MIDPOINT, Datos optimizados [np.int64(12), np.int64(69)]

hit ratio: 0.6111111111111112
risk reward: 0.4494795984157695
profit factor: 1.4832826747720391
trades: 54
Resultado de sobre ajuste 0.2506036696406746
Optimizando ventana: 2019-03-04 al 2019-03-29
Resultado obtenido entrenando desde 2019-03-04 hasta 2019-03-29
Método: WMA, Datos optimizados [np.int64(11), np.int64(88)]

hit ratio: 0.7837837837837838
risk reward: 0.2838239416877001
profit factor: 1.0288617886179128
trades: 37
Resultado de sobre ajuste -1.0904642746013091
Optimizando ventana: 2019-03-11 al 2019-04-05
Resultado obtenido entrenando desde 2019-03-11 hasta 2019-04-05
Método: TEMA, Datos optimizados [np.int64(5), np.int64(4)]

hit ratio: 0.572
risk reward: 0.9281682603110718
profit factor: 1.4348979591836029
trades: 500
Resultado de sobre ajuste 0.4086878782416232
Optimizando ventana: 2019-03-18 al 2019-04-12
Resultado obtenido entrenando desde 2019-03-18 hasta 2019-04-12
Método: SMA, Datos optimizados [np.int64(12), np.int64(80)]

hit ratio: 0.7631578947368421
risk reward: 0.2954460802571941
profit factor: 1.2239909039226613
trades: 38
Resultado de sobre ajuste -0.11103630817939794
Optimizando ventana: 2019-03-25 al 2019-04-19
Resultado obtenido entrenando desde 2019-03-25 hasta 2019-04-19
Método: SMA, Datos optimizados [np.int64(15), np.int64(73)]

hit ratio: 0.7647058823529411
risk reward: 0.3740639891082327
profit factor: 1.3893805309734357
trades: 34
Resultado de sobre ajuste 0.5859148043482434
Optimizando ventana: 2019-04-01 al 2019-04-26
Resultado obtenido entrenando desde 2019-04-01 hasta 2019-04-26
Método: TEMA, Datos optimizados [np.int64(6), np.int64(80)]

hit ratio: 0.7383177570093458
risk reward: 0.4244692028069455
profit factor: 1.3413226808699477
trades: 107
Resultado de sobre ajuste -0.437076544170128
Optimizando ventana: 2019-04-08 al 2019-05-03
Resultado obtenido entrenando desde 2019-04-08 hasta 2019-05-03
Método: WMA, Datos optimizados [np.int64(1), np.int64(18)]

hit ratio: 0.7297619047619047
risk reward: 0.40634555952518464
profit factor: 1.2091739222763989
trades: 840
Resultado de sobre ajuste -0.7641544435161245
Optimizando ventana: 2019-04-15 al 2019-05-10
Resultado obtenido entrenando desde 2019-04-15 hasta 2019-05-10
Método: DEMA, Datos optimizados [np.int64(3), np.int64(37)]

hit ratio: 0.691358024691358
risk reward: 0.5255926335529054
profit factor: 1.279703803433161
trades: 243
Resultado de sobre ajuste -0.6436135869382719
Optimizando ventana: 2019-04-22 al 2019-05-17
Resultado obtenido entrenando desde 2019-04-22 hasta 2019-05-17
Método: DEMA, Datos optimizados [np.int64(11), np.int64(64)]

hit ratio: 0.7301587301587301
risk reward: 0.3710569235052961
profit factor: 1.0667886550777264
trades: 63
Resultado de sobre ajuste -0.3744614663178385
Optimizando ventana: 2019-04-29 al 2019-05-24
Resultado obtenido entrenando desde 2019-04-29 hasta 2019-05-24
Método: KAMA, Datos optimizados [np.int64(9), np.int64(91)]

hit ratio: 0.7553191489361702
risk reward: 0.49271477050922485
profit factor: 1.5209890741806507
trades: 94
Resultado de sobre ajuste 0.33465747160186843
Optimizando ventana: 2019-05-06 al 2019-05-31
Resultado obtenido entrenando desde 2019-05-06 hasta 2019-05-31
Método: KAMA, Datos optimizados [np.int64(10), np.int64(31)]

hit ratio: 0.7764705882352941
risk reward: 0.43901982790869676
profit factor: 1.609739368998555
trades: 85
Resultado de sobre ajuste 0.8223876615586236
Optimizando ventana: 2019-05-13 al 2019-06-07
Resultado obtenido entrenando desde 2019-05-13 hasta 2019-06-07
Método: DEMA, Datos optimizados [np.int64(20), np.int64(52)]

hit ratio: 0.7105263157894737
risk reward: 0.7058484586574465
profit factor: 1.9057908383751057
trades: 38
Resultado de sobre ajuste -0.2784459448610713
Optimizando ventana: 2019-05-20 al 2019-06-14
Resultado obtenido entrenando desde 2019-05-20 hasta 2019-06-14
Método: MIDPOINT, Datos optimizados [np.int64(6), np.int64(46)]

hit ratio: 0.6455696202531646
risk reward: 0.7030303030303356
profit factor: 2.1090909090910066
trades: 79
Resultado de sobre ajuste 1.3678721112270797
Optimizando ventana: 2019-05-27 al 2019-06-21
Resultado obtenido entrenando desde 2019-05-27 hasta 2019-06-21
Método: MIDPOINT, Datos optimizados [np.int64(19), np.int64(28)]

hit ratio: 0.6153846153846154
risk reward: 0.6884796238244317
profit factor: 2.753918495297727
trades: 39
Resultado de sobre ajuste -0.006828736459448798
Optimizando ventana: 2019-06-03 al 2019-06-28
Resultado obtenido entrenando desde 2019-06-03 hasta 2019-06-28
Método: TRIMA, Datos optimizados [np.int64(20), np.int64(56)]

hit ratio: 0.8695652173913043
risk reward: 0.3770745428973304
profit factor: 3.770745428973304
trades: 23
Resultado de sobre ajuste 1.063108888931776
Optimizando ventana: 2019-06-10 al 2019-07-05
Resultado obtenido entrenando desde 2019-06-10 hasta 2019-07-05
Método: SMA, Datos optimizados [np.int64(8), np.int64(95)]

hit ratio: 0.7407407407407407
risk reward: 0.7767711171661954
profit factor: 4.438692098092545
trades: 54
Resultado de sobre ajuste -0.7256754922886551
Optimizando ventana: 2019-06-17 al 2019-07-12
Resultado obtenido entrenando desde 2019-06-17 hasta 2019-07-12
Método: KAMA, Datos optimizados [np.int64(20), np.int64(10)]

hit ratio: 0.7708333333333334
risk reward: 0.6708921310691597
profit factor: 2.2566371681417188
trades: 48
Resultado de sobre ajuste 1.0881882379207277
Optimizando ventana: 2019-06-24 al 2019-07-19
Resultado obtenido entrenando desde 2019-06-24 hasta 2019-07-19
Método: EMA, Datos optimizados [np.int64(5), np.int64(105)]

hit ratio: 0.8360655737704918
risk reward: 0.3643622397412708
profit factor: 1.858247422680481
trades: 61
Resultado de sobre ajuste 1.2138825482012776
Optimizando ventana: 2019-07-01 al 2019-07-26
Resultado obtenido entrenando desde 2019-07-01 hasta 2019-07-26
Método: SMA, Datos optimizados [np.int64(7), np.int64(18)]

hit ratio: 0.6885245901639344
risk reward: 0.45934114386496144
profit factor: 1.2861552028218919
trades: 122
Resultado de sobre ajuste 0.1430662911867149
Optimizando ventana: 2019-07-08 al 2019-08-02
Resultado obtenido entrenando desde 2019-07-08 hasta 2019-08-02
Método: EMA, Datos optimizados [np.int64(19), np.int64(21)]

hit ratio: 0.6296296296296297
risk reward: 0.767158538056379
profit factor: 1.449077238550938
trades: 27
Resultado de sobre ajuste 0.6160032453812937
Optimizando ventana: 2019-07-15 al 2019-08-09
Resultado obtenido entrenando desde 2019-07-15 hasta 2019-08-09
Método: T3, Datos optimizados [np.int64(20), np.int64(88)]

hit ratio: 0.7857142857142857
risk reward: 0.40177500599663535
profit factor: 2.2097625329814945
trades: 14
Resultado de sobre ajuste 0.5062277316508481
Optimizando ventana: 2019-07-22 al 2019-08-16
Resultado obtenido entrenando desde 2019-07-22 hasta 2019-08-16
Método: SMA, Datos optimizados [np.int64(13), np.int64(95)]

hit ratio: 0.65
risk reward: 0.8713675213675787
profit factor: 2.8319444444446304
trades: 20
Resultado de sobre ajuste 1.0872086501787315
Optimizando ventana: 2019-07-29 al 2019-08-23
Resultado obtenido entrenando desde 2019-07-29 hasta 2019-08-23
Método: EMA, Datos optimizados [np.int64(8), np.int64(31)]

hit ratio: 0.8035714285714286
risk reward: 0.3651304037156312
profit factor: 1.6430868167203403
trades: 56
Resultado de sobre ajuste 1.0811731559531097
Optimizando ventana: 2019-08-05 al 2019-08-30
Resultado obtenido entrenando desde 2019-08-05 hasta 2019-08-30
Método: EMA, Datos optimizados [np.int64(5), np.int64(66)]

hit ratio: 0.8133333333333334
risk reward: 0.361937064254755
profit factor: 1.5770114942528608
trades: 75
Resultado de sobre ajuste 0.8861756441481172
Optimizando ventana: 2019-08-12 al 2019-09-06
Resultado obtenido entrenando desde 2019-08-12 hasta 2019-09-06
Método: TEMA, Datos optimizados [np.int64(9), np.int64(96)]

hit ratio: 0.7142857142857143
risk reward: 0.5317951603826572
profit factor: 1.519414743950449
trades: 56
Resultado de sobre ajuste -0.43681091658688365
Optimizando ventana: 2019-08-19 al 2019-09-13
Resultado obtenido entrenando desde 2019-08-19 hasta 2019-09-13
Método: EMA, Datos optimizados [np.int64(4), np.int64(36)]

hit ratio: 0.816793893129771
risk reward: 0.325689723010799
profit factor: 1.5151652331371954
trades: 131
Resultado de sobre ajuste 1.0859077724973687
Optimizando ventana: 2019-08-26 al 2019-09-20
Resultado obtenido entrenando desde 2019-08-26 hasta 2019-09-20
Método: SMA, Datos optimizados [np.int64(4), np.int64(13)]

hit ratio: 0.7377777777777778
risk reward: 0.43471052615827893
profit factor: 1.3877297565821982
trades: 225
Resultado de sobre ajuste 0.3502757638520588
Optimizando ventana: 2019-09-02 al 2019-09-27
Resultado obtenido entrenando desde 2019-09-02 hasta 2019-09-27
Método: EMA, Datos optimizados [np.int64(15), np.int64(49)]

hit ratio: 0.8461538461538461
risk reward: 0.2214679260133811
profit factor: 1.6240981240981283
trades: 26
Resultado de sobre ajuste 0.6133765994617658
Optimizando ventana: 2019-09-09 al 2019-10-04
Resultado obtenido entrenando desde 2019-09-09 hasta 2019-10-04
Método: WMA, Datos optimizados [np.int64(18), np.int64(36)]

hit ratio: 0.6041666666666666
risk reward: 0.6047404563242983
profit factor: 1.2526766595289036
trades: 48
Resultado de sobre ajuste -0.19469911419809555
Optimizando ventana: 2019-09-16 al 2019-10-11
Resultado obtenido entrenando desde 2019-09-16 hasta 2019-10-11
Método: T3, Datos optimizados [np.int64(17), np.int64(28)]

hit ratio: 0.6842105263157895
risk reward: 0.4379874598562529
profit factor: 1.423459244532822
trades: 38
Resultado de sobre ajuste 0.45027851864152635
Optimizando ventana: 2019-09-23 al 2019-10-18
Resultado obtenido entrenando desde 2019-09-23 hasta 2019-10-18
Método: TRIMA, Datos optimizados [np.int64(8), np.int64(31)]

hit ratio: 0.6617647058823529
risk reward: 0.6359647429711489
profit factor: 1.7886508396063565
trades: 68
Resultado de sobre ajuste 0.6299166547735289
Optimizando ventana: 2019-09-30 al 2019-10-25
Resultado obtenido entrenando desde 2019-09-30 hasta 2019-10-25
Método: SMA, Datos optimizados [np.int64(9), np.int64(51)]

hit ratio: 0.75
risk reward: 0.6041737168640594
profit factor: 4.531302876480446
trades: 60
Resultado de sobre ajuste 2.6109691178980157
Optimizando ventana: 2019-10-07 al 2019-11-01
Resultado obtenido entrenando desde 2019-10-07 hasta 2019-11-01
Método: MIDPOINT, Datos optimizados [np.int64(8), np.int64(92)]

hit ratio: 0.5882352941176471
risk reward: 0.7337164750958348
profit factor: 2.2011494252875043
trades: 51
Resultado de sobre ajuste 1.203791269555967
Optimizando ventana: 2019-10-14 al 2019-11-08
Resultado obtenido entrenando desde 2019-10-14 hasta 2019-11-08
Método: SMA, Datos optimizados [np.int64(2), np.int64(76)]

hit ratio: 0.7671232876712328
risk reward: 0.5284178659178245
profit factor: 2.040786240786081
trades: 146
Resultado de sobre ajuste 0.760685504378628
Optimizando ventana: 2019-10-21 al 2019-11-15
Resultado obtenido entrenando desde 2019-10-21 hasta 2019-11-15
Método: MIDPOINT, Datos optimizados [np.int64(13), np.int64(105)]

hit ratio: 0.71875
risk reward: 0.416812706890315
profit factor: 1.1983365323096558
trades: 32
Resultado de sobre ajuste -0.18204367128345128
Optimizando ventana: 2019-10-28 al 2019-11-22
Resultado obtenido entrenando desde 2019-10-28 hasta 2019-11-22
Método: T3, Datos optimizados [np.int64(6), np.int64(35)]

hit ratio: 0.625
risk reward: 0.892712550607254
profit factor: 1.912955465586973
trades: 72
Resultado de sobre ajuste 0.05470934029808232
Optimizando ventana: 2019-11-04 al 2019-11-29
Resultado obtenido entrenando desde 2019-11-04 hasta 2019-11-29
Método: DEMA, Datos optimizados [np.int64(15), np.int64(34)]

hit ratio: 0.71875
risk reward: 0.7083333333332689
profit factor: 1.9166666666664922
trades: 64
Resultado de sobre ajuste -1.1802586901045888
Optimizando ventana: 2019-11-11 al 2019-12-06
Resultado obtenido entrenando desde 2019-11-11 hasta 2019-12-06
Método: WMA, Datos optimizados [np.int64(4), np.int64(49)]

hit ratio: 0.7517241379310344
risk reward: 0.5029146707801966
profit factor: 2.2840707964600595
trades: 145
Resultado de sobre ajuste 0.8848918085963804
Optimizando ventana: 2019-11-18 al 2019-12-13
Resultado obtenido entrenando desde 2019-11-18 hasta 2019-12-13
Método: T3, Datos optimizados [np.int64(16), np.int64(10)]

hit ratio: 0.6029411764705882
risk reward: 0.6977481284713919
profit factor: 1.9071782178218046
trades: 68
Resultado de sobre ajuste 0.27732417729905384
Optimizando ventana: 2019-11-25 al 2019-12-20
Resultado obtenido entrenando desde 2019-11-25 hasta 2019-12-20
Método: MIDPOINT, Datos optimizados [np.int64(14), np.int64(106)]

hit ratio: 0.8285714285714286
risk reward: 0.3436260963594752
profit factor: 2.4912891986061956
trades: 35
Resultado de sobre ajuste 1.1649448519209264
Optimizando ventana: 2019-12-02 al 2019-12-27
Resultado obtenido entrenando desde 2019-12-02 hasta 2019-12-27
Método: SMA, Datos optimizados [np.int64(20), np.int64(74)]

hit ratio: 0.7586206896551724
risk reward: 0.2702020202019987
profit factor: 1.9814814814813237
trades: 29
Resultado de sobre ajuste -0.7129858672475059
Optimizando ventana: 2019-12-09 al 2020-01-03
Resultado obtenido entrenando desde 2019-12-09 hasta 2020-01-03
Método: TEMA, Datos optimizados [np.int64(15), np.int64(41)]

hit ratio: 0.6909090909090909
risk reward: 0.8783258885220315
profit factor: 2.22509225092248
trades: 55
Resultado de sobre ajuste -0.6775589115640454
Optimizando ventana: 2019-12-16 al 2020-01-10
Resultado obtenido entrenando desde 2019-12-16 hasta 2020-01-10
Método: TEMA, Datos optimizados [np.int64(8), np.int64(102)]

hit ratio: 0.6
risk reward: 0.5669231499952558
profit factor: 0.9354231974921721
trades: 55
Resultado de sobre ajuste -0.7665721406163515
Optimizando ventana: 2019-12-23 al 2020-01-17
Resultado obtenido entrenando desde 2019-12-23 hasta 2020-01-17
Método: TEMA, Datos optimizados [np.int64(10), np.int64(30)]

hit ratio: 0.6022727272727273
risk reward: 0.8693038241240193
profit factor: 1.5887276785714834
trades: 88
Resultado de sobre ajuste -0.03110015868832791
Optimizando ventana: 2019-12-30 al 2020-01-24
Resultado obtenido entrenando desde 2019-12-30 hasta 2020-01-24
Método: EMA, Datos optimizados [np.int64(7), np.int64(13)]

hit ratio: 0.7477477477477478
risk reward: 0.4340506129320552
profit factor: 1.3343037360503918
trades: 111
Resultado de sobre ajuste 0.8114811125220616
Optimizando ventana: 2020-01-06 al 2020-01-31
Resultado obtenido entrenando desde 2020-01-06 hasta 2020-01-31
Método: KAMA, Datos optimizados [np.int64(7), np.int64(104)]

hit ratio: 0.8076923076923077
risk reward: 0.3267893860765784
profit factor: 1.5250171350240325
trades: 104
Resultado de sobre ajuste -0.8279432609761125
Optimizando ventana: 2020-01-13 al 2020-02-07
Resultado obtenido entrenando desde 2020-01-13 hasta 2020-02-07
Método: TEMA, Datos optimizados [np.int64(20), np.int64(28)]

hit ratio: 0.5692307692307692
risk reward: 0.6861569300287471
profit factor: 1.0578252671276518
trades: 65
Resultado de sobre ajuste 0.042179768412709887
Optimizando ventana: 2020-01-20 al 2020-02-14
Resultado obtenido entrenando desde 2020-01-20 hasta 2020-02-14
Método: MIDPOINT, Datos optimizados [np.int64(14), np.int64(29)]

hit ratio: 0.5636363636363636
risk reward: 0.43672456575682383
profit factor: 0.8461538461538461
trades: 55
Resultado de sobre ajuste -1.8093487392329348
Optimizando ventana: 2020-01-27 al 2020-02-21
Resultado obtenido entrenando desde 2020-01-27 hasta 2020-02-21
Método: TEMA, Datos optimizados [np.int64(20), np.int64(38)]

hit ratio: 0.5932203389830508
risk reward: 0.7479054779806434
profit factor: 1.1898496240601144
trades: 59
Resultado de sobre ajuste -1.3658375245854353
Optimizando ventana: 2020-02-03 al 2020-02-28
Resultado obtenido entrenando desde 2020-02-03 hasta 2020-02-28
Método: TEMA, Datos optimizados [np.int64(19), np.int64(77)]

hit ratio: 0.6190476190476191
risk reward: 0.6982002177672054
profit factor: 1.6502914238133946
trades: 42
Resultado de sobre ajuste -0.6994249184045799
Optimizando ventana: 2020-02-10 al 2020-03-06
Resultado obtenido entrenando desde 2020-02-10 hasta 2020-03-06
Método: KAMA, Datos optimizados [np.int64(9), np.int64(81)]

hit ratio: 0.9213483146067416
risk reward: 0.20980970249263237
profit factor: 2.867399267399309
trades: 89
Resultado de sobre ajuste 1.839935479514954
Optimizando ventana: 2020-02-17 al 2020-03-13
Resultado obtenido entrenando desde 2020-02-17 hasta 2020-03-13
Método: SMA, Datos optimizados [np.int64(12), np.int64(105)]

hit ratio: 0.7586206896551724
risk reward: 2.959637872500939
profit factor: 16.27800829875516
trades: 29
Resultado de sobre ajuste 2.805997940253888
Optimizando ventana: 2020-02-24 al 2020-03-20
Resultado obtenido entrenando desde 2020-02-24 hasta 2020-03-20
Método: KAMA, Datos optimizados [np.int64(9), np.int64(71)]

hit ratio: 0.8571428571428571
risk reward: 0.18823746312684672
profit factor: 1.2320997586484512
trades: 84
Resultado de sobre ajuste -1.0824754326006363
Optimizando ventana: 2020-03-02 al 2020-03-27
Resultado obtenido entrenando desde 2020-03-02 hasta 2020-03-27
Método: DEMA, Datos optimizados [np.int64(13), np.int64(100)]

hit ratio: 0.6590909090909091
risk reward: 0.6251031009883158
profit factor: 1.394460763743166
trades: 44
Resultado de sobre ajuste -0.8830468892064365
Optimizando ventana: 2020-03-09 al 2020-04-03
Resultado obtenido entrenando desde 2020-03-09 hasta 2020-04-03
Método: DEMA, Datos optimizados [np.int64(8), np.int64(9)]

hit ratio: 0.6223404255319149
risk reward: 0.5589248110987252
profit factor: 0.9342028985507264
trades: 188