In [1]:
# lectura de los datos

import pandas as pd
import read_data

# Suponiendo que el activo tiene ese nombre
# solo es remplazar por el nombre que se tenga
# solo se acepta archivos .parquet y .csv
nombre_activo: str = "EURUSD_2019-2025.parquet"
data: pd.DataFrame = pd.read_parquet(f"Data/{nombre_activo}")

primer_lunes = data[data.index.dayofweek == 0].index[0]
ultimo_viernes = data[data.index.dayofweek == 4].index[-1]

data = data.loc[primer_lunes: ultimo_viernes]
data = data.between_time('07:00', '16:00')
data

                     Precio Spot
time
2019-01-07 07:00:00     1.142020
2019-01-07 07:01:00     1.142060
2019-01-07 07:02:00     1.142060
2019-01-07 07:03:00     1.142180
2019-01-07 07:04:00     1.142170
...                          ...
2026-02-13 15:56:00     1.187810
2026-02-13 15:57:00     1.187695
2026-02-13 15:58:00     1.187485
2026-02-13 15:59:00     1.187420
2026-02-13 16:00:00     1.187060

[1052237 rows x 1 columns]

In [2]:
import numpy as np
import pandas as pd

ma_week = []

with open("Data/Moving_average.txt", "r") as archivo:

    for line in archivo:
        start = pd.Timestamp(line[:10])
        fin = pd.Timestamp(line[11:21])

        lista = eval(line[22: ], {"np": np})

        ma_week.append([start, fin, lista])

In [3]:
import train_network

X, y = train_network.build_weekly_dataset(data, ma_week)

Calculando matemáticas avanzadas para timeframe 13min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 11min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 12min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 14min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 19min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 8min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 15min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 16min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 4min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 10min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 5min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 20min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 3min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 17min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 1min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 9min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 2min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 18min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 7min (solo se hace una vez)...
Calculando matemáticas avanzadas para timeframe 6min (solo se hace una vez)...

In [5]:
import train_network

model = train_network.train_model(X, y)

              precision    recall  f1-score   support

           0       0.66      0.60      0.63      6852
           1       0.64      0.70      0.67      7034

    accuracy                           0.65     13886
   macro avg       0.65      0.65      0.65     13886
weighted avg       0.65      0.65      0.65     13886

In [16]:
import joblib

nombre_archivo = "modelo_filtro_ma.joblib"
joblib.dump(model, nombre_archivo)

print(f"¡Modelo guardado exitosamente como {nombre_archivo}!")

¡Modelo guardado exitosamente como modelo_filtro_ma.joblib!

In [5]:
import deep_clasificador

X, y = deep_clasificador.build_cnn_dataset(data, ma_week)

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1774288808.034759   72754 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
I0000 00:00:1774288808.098116   72754 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1774288811.082284   72754 cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.

In [6]:
model = deep_clasificador.train_cnn_model(X, y)

model.save("Modelo_clasificador_deep.keras")

/home/angel/Documents/optimal-moving-average/opt_m/lib/python3.13/site-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
E0000 00:00:1774289169.862837   72754 cuda_platform.cc:52] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)

Iniciando el entrenamiento con 47565 muestras...
Features utilizados por ventana: 8
Epoch 1/58

W0000 00:00:1774289171.485658   72754 cpu_allocator_impl.cc:82] Allocation of 91324800 exceeds 10% of free system memory.

1487/1487 ━━━━━━━━━━━━━━━━━━━━ 40s 22ms/step - accuracy: 0.5090 - loss: 0.6894 - val_accuracy: 0.4872 - val_loss: 0.6851
Epoch 2/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 26s 17ms/step - accuracy: 0.5155 - loss: 0.6851 - val_accuracy: 0.4911 - val_loss: 0.6828
Epoch 3/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 26s 18ms/step - accuracy: 0.5115 - loss: 0.6838 - val_accuracy: 0.4793 - val_loss: 0.6879
Epoch 4/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 27s 18ms/step - accuracy: 0.5190 - loss: 0.6823 - val_accuracy: 0.4991 - val_loss: 0.6835
Epoch 5/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 17s 12ms/step - accuracy: 0.5243 - loss: 0.6817 - val_accuracy: 0.5011 - val_loss: 0.6845
Epoch 6/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 25s 17ms/step - accuracy: 0.5262 - loss: 0.6811 - val_accuracy: 0.4888 - val_loss: 0.6887
Epoch 7/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 23s 16ms/step - accuracy: 0.5271 - loss: 0.6809 - val_accuracy: 0.4756 - val_loss: 0.6946
Epoch 8/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 25s 17ms/step - accuracy: 0.5306 - loss: 0.6803 - val_accuracy: 0.4971 - val_loss: 0.6893
Epoch 9/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 27s 18ms/step - accuracy: 0.5346 - loss: 0.6796 - val_accuracy: 0.4906 - val_loss: 0.6894
Epoch 10/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 32s 12ms/step - accuracy: 0.5386 - loss: 0.6787 - val_accuracy: 0.5117 - val_loss: 0.6847
Epoch 11/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 12s 8ms/step - accuracy: 0.5369 - loss: 0.6785 - val_accuracy: 0.4956 - val_loss: 0.6936
Epoch 12/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 22s 15ms/step - accuracy: 0.5408 - loss: 0.6774 - val_accuracy: 0.5065 - val_loss: 0.6847
Epoch 13/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 27s 18ms/step - accuracy: 0.5433 - loss: 0.6770 - val_accuracy: 0.4891 - val_loss: 0.6947
Epoch 14/58
1487/1487 ━━━━━━━━━━━━━━━━━━━━ 25s 17ms/step - accuracy: 0.5459 - loss: 0.6760 - val_accuracy: 0.5034 - val_loss: 0.6914
Epoch 14: early stopping
Restoring model weights from the end of the best epoch: 2.

--- Evaluación en el conjunto de prueba (Datos no vistos) ---
638/638 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step

Reporte de Clasificación (Umbral: 0.6):
              precision    recall  f1-score   support

Rechazar (0)       0.60      1.00      0.75     12228
  Operar (1)       0.00      0.00      0.00      8157

    accuracy                           0.60     20385
   macro avg       0.30      0.50      0.37     20385
weighted avg       0.36      0.60      0.45     20385

/home/angel/Documents/optimal-moving-average/opt_m/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/angel/Documents/optimal-moving-average/opt_m/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
/home/angel/Documents/optimal-moving-average/opt_m/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1833: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

In [3]:
import joblib

model = joblib.load("modelo_filtro_ma.joblib")

In [4]:
from tester import backtest
from use_tecnics import main

def get_info_in_week(data: pd.DataFrame, week: list) -> pd.DataFrame:
    time_col = week[0] - pd.Timedelta(weeks=1)
    data_week_raw = data.loc[time_col: week[1]]
    velas_cerradas = read_data.ohlc_form(data_week_raw, f"{week[2][1]}min")["close"]
    method_name = week[2][0]
    params = week[2][2]
    
    df_week = main(method_name, velas_cerradas, params)
    df_week = df_week.loc[week[0]: week[1]]
    
    if len(df_week) == 0:
        return pd.DataFrame()

    f_i = df_week.index[0]
    l_i = df_week.index[-1]
    if df_week["Signals"][f_i] == -1:
        f_i = df_week.index[1] if len(df_week) > 1 else f_i
    if df_week["Signals"][l_i] == 1:
        l_i = df_week.index[-2] if len(df_week) > 1 else l_i

    return df_week.loc[f_i: l_i]

def get_signals_and_prices(data: pd.DataFrame, ma_week: list) -> pd.DataFrame:
    signals_and_prices = None
    for week in ma_week:
        data_week = get_info_in_week(data, week)

        if signals_and_prices is None:
            signals_and_prices = data_week
        else:
            signals_and_prices = pd.concat([signals_and_prices, data_week])
    return signals_and_prices

signals_and_prices_c = get_signals_and_prices(data, ma_week)
backtest(signals_and_prices_c)

(np.float64(0.7516522333637192),
 np.float64(0.32950633809660357),
 np.float64(1.1152327138297822),
 35104)

In [5]:
from train_network import filter_signals_with_ml

signals_and_prices = filter_signals_with_ml(signals_and_prices_c, data, model, umbral=.6)

In [21]:
backtest(signals_and_prices)

(np.float64(0.8461538461538461),
 np.float64(0.5079688586267431),
 np.float64(2.869337606837549),
 247)

In [16]:
signals_and_prices = signals_and_prices.loc[signals_and_prices["Signals"] != 0]
signals_and_prices = signals_and_prices.loc[signals_and_prices["Signals"] != signals_and_prices["Signals"].shift(1)]
signals_and_prices

                     Signals    Prices
time
2025-04-02 23:24:00        1  1.083615
2025-04-02 23:51:00       -1  1.086025
2025-04-03 00:09:00        1  1.082920
2025-04-03 02:06:00       -1  1.085520
2025-04-03 18:36:00        1  1.104500
...                      ...       ...
2026-02-11 09:52:00       -1  1.191690
2026-02-11 17:06:00        1  1.185830
2026-02-11 18:16:00       -1  1.187020
2026-02-12 18:04:00        1  1.186730
2026-02-12 19:14:00       -1  1.187260

[494 rows x 2 columns]

In [37]:
from deep_clasificador import filter_signals_with_cnn

signals_and_prices = filter_signals_with_cnn(signals_and_prices_c, data, model, 30, .6)
backtest(signals_and_prices)

(np.float64(1.0), 0.0, 0.0, 2)

In [38]:
import pandas as pd
import matplotlib.pyplot as plt

def simular_trading_basico(señales_precios, capital_inicial=10000.0, valor_pip=0.0001):
    compradas = 0
    capital_operativo = capital_inicial

    pico_maximo = capital_inicial
    max_drawdown = 0.0
    
    for idx in señales_precios.index:
        precio_actual = señales_precios["Prices"][idx]
        senal = señales_precios["Signals"][idx]

        if senal == 1:
            precio_compra = precio_actual + valor_pip
            if capital_operativo >= precio_compra:
                nuevas_compras = int(capital_operativo / precio_compra)
                compradas += nuevas_compras
                capital_operativo -= nuevas_compras * precio_compra

        elif senal == -1: 
            precio_venta = precio_actual - valor_pip
            capital_operativo += compradas * precio_venta
            compradas = 0
                
        patrimonio_actual = capital_operativo + (compradas * precio_actual)

        if patrimonio_actual > pico_maximo:
            pico_maximo = patrimonio_actual
            
        drawdown_actual = (pico_maximo - patrimonio_actual) / pico_maximo
        
        if drawdown_actual > max_drawdown:
            max_drawdown = drawdown_actual

    print(f"--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---")
    print(f"Patrimonio Total Final: ${patrimonio_actual:.2f}")
    print(f"Capital Inicial: ${capital_inicial:.2f}")
    print(f"Beneficio Neto: ${(patrimonio_actual - capital_inicial):.2f}")
    print(f"Max Drawdown: {max_drawdown * 100:.2f}%\n")
    
    return patrimonio_actual, max_drawdown

simular_trading_basico(signals_and_prices_c)
simular_trading_basico(signals_and_prices)
print("")

--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---
Patrimonio Total Final: $5724.27
Capital Inicial: $10000.00
Beneficio Neto: $-4275.73
Max Drawdown: 42.78%

--- RESULTADOS DEL SIMULADOR (INTERÉS COMPUESTO) ---
Patrimonio Total Final: $9999.49
Capital Inicial: $10000.00
Beneficio Neto: $-0.51
Max Drawdown: 0.01%

In [24]:
import pandas as pd
import find_best
import keys
from use_tecnics import simple_methods

keys.methods = simple_methods
keys.candles = 1
keys.calls = 20

dias_comp_sem = pd.Timedelta(days=4)
next_lun = pd.Timedelta(days=3)
ventana_ent = pd.Timedelta(weeks=3) + dias_comp_sem

primer_lunes = data[data.index.dayofweek == 0].index[0]
ultimo_viernes = data[data.index.dayofweek == 4].index[-1]

inicio_actual = primer_lunes

with open("Data/Moving_average.txt", "w") as archivo:
    archivo.write("") 

while True:
    train_time_init = inicio_actual
    train_time_fin = inicio_actual + ventana_ent

    test_time_init = train_time_fin + next_lun
    test_time_fin = test_time_init + dias_comp_sem

    if train_time_fin >= ultimo_viernes:
        break

    print(f"Optimizando ventana: {train_time_init.date()} al {train_time_fin.date()}")

    data_w = data.loc[train_time_init : train_time_fin]
    
    if len(data_w) < 100:
        inicio_actual += (dias_comp_sem + next_lun)
        continue

    best_ma = find_best.opti_main(data_w)

    with open("Data/Moving_average.txt", "a") as archivo:
        archivo.write(f"{test_time_init.date()} {test_time_fin.date()}, {best_ma}\n")

    inicio_actual += (dias_comp_sem + next_lun)

Optimizando ventana: 2019-01-07 al 2019-02-01
Resultado obtenido entrenando desde 2019-01-07 hasta 2019-02-01
Método: EMA, Datos optimizados [1, np.int64(52)]

hit ratio: 0.8231292517006803
risk reward: 0.3207754880622209
profit factor: 1.5950890707751533
trades: 441
Resultado de sobre ajuste 0.3582436435836891
Optimizando ventana: 2019-01-14 al 2019-02-08
Resultado obtenido entrenando desde 2019-01-14 hasta 2019-02-08
Método: EMA, Datos optimizados [1, np.int64(98)]

hit ratio: 0.8534201954397395
risk reward: 0.27076062802355655
profit factor: 1.730226452248093
trades: 307
Resultado de sobre ajuste 0.14368681397600472
Optimizando ventana: 2019-01-21 al 2019-02-15
Resultado obtenido entrenando desde 2019-01-21 hasta 2019-02-15
Método: MIDPOINT, Datos optimizados [1, np.int64(46)]

hit ratio: 0.7551546391752577
risk reward: 0.3326676957792879
profit factor: 1.1467251160391922
trades: 388
Resultado de sobre ajuste -0.3352712770147418
Optimizando ventana: 2019-01-28 al 2019-02-22
Resultado obtenido entrenando desde 2019-01-28 hasta 2019-02-22
Método: EMA, Datos optimizados [1, np.int64(87)]

hit ratio: 0.8243243243243243
risk reward: 0.28546998466799667
profit factor: 1.482014388489174
trades: 296
Resultado de sobre ajuste -0.039620203720740495
Optimizando ventana: 2019-02-04 al 2019-03-01
Resultado obtenido entrenando desde 2019-02-04 hasta 2019-03-01
Método: EMA, Datos optimizados [1, np.int64(94)]

hit ratio: 0.8388278388278388
risk reward: 0.22106518070028183
profit factor: 1.1773006134968498
trades: 273
Resultado de sobre ajuste -0.4559421131627914
Optimizando ventana: 2019-02-11 al 2019-03-08
Resultado obtenido entrenando desde 2019-02-11 hasta 2019-03-08
Método: T3, Datos optimizados [1, np.int64(31)]

hit ratio: 0.6995305164319249
risk reward: 0.3147863998330993
profit factor: 1.218264248704722
trades: 426
Resultado de sobre ajuste 0.007096389810947994
Optimizando ventana: 2019-02-18 al 2019-03-15
Resultado obtenido entrenando desde 2019-02-18 hasta 2019-03-15
Método: SMA, Datos optimizados [1, np.int64(61)]

hit ratio: 0.8136482939632546
risk reward: 0.27503665689148443
profit factor: 1.4958133971291259
trades: 381
Resultado de sobre ajuste 0.34880291797515717
Optimizando ventana: 2019-02-25 al 2019-03-22
Resultado obtenido entrenando desde 2019-02-25 hasta 2019-03-22
Método: KAMA, Datos optimizados [1, np.int64(36)]

hit ratio: 0.8181818181818182
risk reward: 0.30056689342401294
profit factor: 1.506249999999883
trades: 539
Resultado de sobre ajuste 0.30286549375081395
Optimizando ventana: 2019-03-04 al 2019-03-29
Resultado obtenido entrenando desde 2019-03-04 hasta 2019-03-29
Método: T3, Datos optimizados [1, np.int64(86)]

hit ratio: 0.7763713080168776
risk reward: 0.21962944515079708
profit factor: 1.2246005426589899
trades: 237
Resultado de sobre ajuste -0.26580712791966726
Optimizando ventana: 2019-03-11 al 2019-04-05
Resultado obtenido entrenando desde 2019-03-11 hasta 2019-04-05
Método: TEMA, Datos optimizados [1, np.int64(35)]

hit ratio: 0.6899879372738239
risk reward: 0.4587775299562616
profit factor: 1.1166840303616241
trades: 829
Resultado de sobre ajuste -0.32017710405271527
Optimizando ventana: 2019-03-18 al 2019-04-12
Resultado obtenido entrenando desde 2019-03-18 hasta 2019-04-12
Método: SMA, Datos optimizados [1, np.int64(76)]

hit ratio: 0.8233618233618234
risk reward: 0.19837580441743444
profit factor: 1.146612149532771
trades: 351
Resultado de sobre ajuste -0.20180736825756249
Optimizando ventana: 2019-03-25 al 2019-04-19
Resultado obtenido entrenando desde 2019-03-25 hasta 2019-04-19
Método: MIDPOINT, Datos optimizados [1, np.int64(10)]

hit ratio: 0.6953125
risk reward: 0.47820386097268924
profit factor: 1.1822262118491484
trades: 896
Resultado de sobre ajuste 0.4856977921258
Optimizando ventana: 2019-04-01 al 2019-04-26
Resultado obtenido entrenando desde 2019-04-01 hasta 2019-04-26
Método: WMA, Datos optimizados [1, np.int64(75)]

hit ratio: 0.802439024390244
risk reward: 0.2874148182937829
profit factor: 1.295335276967871
trades: 410
Resultado de sobre ajuste 0.5512787606899675
Optimizando ventana: 2019-04-08 al 2019-05-03
Resultado obtenido entrenando desde 2019-04-08 hasta 2019-05-03
Método: DEMA, Datos optimizados [1, np.int64(34)]

hit ratio: 0.7356643356643356
risk reward: 0.3607314603353963
profit factor: 1.1294330246215385
trades: 715
Resultado de sobre ajuste 0.1736149019312998
Optimizando ventana: 2019-04-15 al 2019-05-10
Resultado obtenido entrenando desde 2019-04-15 hasta 2019-05-10
Método: SMA, Datos optimizados [1, np.int64(34)]

hit ratio: 0.782520325203252
risk reward: 0.3206120035191544
profit factor: 1.313144908030579
trades: 492
Resultado de sobre ajuste 0.1316754224815857
Optimizando ventana: 2019-04-22 al 2019-05-17
Resultado obtenido entrenando desde 2019-04-22 hasta 2019-05-17
Método: SMA, Datos optimizados [1, np.int64(17)]

hit ratio: 0.721030042918455
risk reward: 0.41976357707262285
profit factor: 1.1952589991220448
trades: 699
Resultado de sobre ajuste -0.016999047640999475
Optimizando ventana: 2019-04-29 al 2019-05-24
Resultado obtenido entrenando desde 2019-04-29 hasta 2019-05-24
Método: T3, Datos optimizados [1, np.int64(62)]

hit ratio: 0.6914498141263941
risk reward: 0.35006920850635975
profit factor: 1.2521706304265945
trades: 269
Resultado de sobre ajuste 0.3625812216733831
Optimizando ventana: 2019-05-06 al 2019-05-31
Resultado obtenido entrenando desde 2019-05-06 hasta 2019-05-31
Método: KAMA, Datos optimizados [1, np.int64(105)]

hit ratio: 0.790948275862069
risk reward: 0.31951650651493807
profit factor: 1.5429283933023985
trades: 464
Resultado de sobre ajuste 0.19744775805473253
Optimizando ventana: 2019-05-13 al 2019-06-07
Resultado obtenido entrenando desde 2019-05-13 hasta 2019-06-07
Método: EMA, Datos optimizados [1, np.int64(110)]

hit ratio: 0.823321554770318
risk reward: 0.283597045441973
profit factor: 1.436480686695211
trades: 283
Resultado de sobre ajuste -0.019497892676697826
Optimizando ventana: 2019-05-20 al 2019-06-14
Resultado obtenido entrenando desde 2019-05-20 hasta 2019-06-14
Método: SMA, Datos optimizados [1, np.int64(82)]

hit ratio: 0.7543859649122807
risk reward: 0.36698189579038004
profit factor: 1.3603639240505467
trades: 285
Resultado de sobre ajuste 0.38911600826271897
Optimizando ventana: 2019-05-27 al 2019-06-21
Resultado obtenido entrenando desde 2019-05-27 hasta 2019-06-21
Método: MIDPOINT, Datos optimizados [1, np.int64(97)]

hit ratio: 0.7421875
risk reward: 0.31537864609484395
profit factor: 1.2228967909800073
trades: 256
Resultado de sobre ajuste 0.16423494103066924
Optimizando ventana: 2019-06-03 al 2019-06-28
Resultado obtenido entrenando desde 2019-06-03 hasta 2019-06-28
Método: T3, Datos optimizados [1, np.int64(108)]

hit ratio: 0.7817258883248731
risk reward: 0.23977024153700696
profit factor: 1.2732626619551404
trades: 197
Resultado de sobre ajuste 0.5704866744036049
Optimizando ventana: 2019-06-10 al 2019-07-05
Resultado obtenido entrenando desde 2019-06-10 hasta 2019-07-05
Método: MIDPOINT, Datos optimizados [1, np.int64(82)]

hit ratio: 0.7911764705882353
risk reward: 0.2850345440943388
profit factor: 1.446684761535418
trades: 340
Resultado de sobre ajuste -0.04466330452046198
Optimizando ventana: 2019-06-17 al 2019-07-12
Resultado obtenido entrenando desde 2019-06-17 hasta 2019-07-12
Método: WMA, Datos optimizados [1, np.int64(73)]

hit ratio: 0.7897196261682243
risk reward: 0.3459619928509327
profit factor: 1.5802047781569628
trades: 428
Resultado de sobre ajuste 0.8402298281320968
Optimizando ventana: 2019-06-24 al 2019-07-19
Resultado obtenido entrenando desde 2019-06-24 hasta 2019-07-19
Método: MIDPOINT, Datos optimizados [1, np.int64(85)]

hit ratio: 0.7988668555240793
risk reward: 0.2539867465846728
profit factor: 1.3514011799410892
trades: 353
Resultado de sobre ajuste 0.4502381829036963
Optimizando ventana: 2019-07-01 al 2019-07-26
Resultado obtenido entrenando desde 2019-07-01 hasta 2019-07-26
Método: MIDPOINT, Datos optimizados [1, np.int64(74)]

hit ratio: 0.7933884297520661
risk reward: 0.26281227038947536
profit factor: 1.282880235121507
trades: 363
Resultado de sobre ajuste 0.44805199340778035
Optimizando ventana: 2019-07-08 al 2019-08-02
Resultado obtenido entrenando desde 2019-07-08 hasta 2019-08-02
Método: EMA, Datos optimizados [1, np.int64(56)]

hit ratio: 0.8270142180094787
risk reward: 0.29648201209804675
profit factor: 1.591880341880282
trades: 422
Resultado de sobre ajuste 0.1912608728719584
Optimizando ventana: 2019-07-15 al 2019-08-09
Resultado obtenido entrenando desde 2019-07-15 hasta 2019-08-09
Método: EMA, Datos optimizados [1, np.int64(65)]

hit ratio: 0.8290155440414507
risk reward: 0.29973631916844856
profit factor: 1.5985937022317256
trades: 386
Resultado de sobre ajuste 0.3116462770927417
Optimizando ventana: 2019-07-22 al 2019-08-16
Resultado obtenido entrenando desde 2019-07-22 hasta 2019-08-16
Método: MIDPOINT, Datos optimizados [1, np.int64(37)]

hit ratio: 0.7682926829268293
risk reward: 0.3228865614476555
profit factor: 1.470495424424262
trades: 492
Resultado de sobre ajuste 0.190814522406257
Optimizando ventana: 2019-07-29 al 2019-08-23
Resultado obtenido entrenando desde 2019-07-29 hasta 2019-08-23
Método: MIDPOINT, Datos optimizados [1, np.int64(23)]

hit ratio: 0.7111111111111111
risk reward: 0.45872870418172046
profit factor: 1.372885906040257
trades: 585
Resultado de sobre ajuste 0.13344114843042565
Optimizando ventana: 2019-08-05 al 2019-08-30
Resultado obtenido entrenando desde 2019-08-05 hasta 2019-08-30
Método: MIDPOINT, Datos optimizados [1, np.int64(69)]

hit ratio: 0.7965686274509803
risk reward: 0.30554945054945565
profit factor: 1.482142857142882
trades: 408
Resultado de sobre ajuste 0.4721845752289339
Optimizando ventana: 2019-08-12 al 2019-09-06
Resultado obtenido entrenando desde 2019-08-12 hasta 2019-09-06
Método: MIDPOINT, Datos optimizados [1, np.int64(105)]

hit ratio: 0.8377581120943953
risk reward: 0.27317607613817146
profit factor: 1.9395501405810174
trades: 339
Resultado de sobre ajuste 1.2556274679487658
Optimizando ventana: 2019-08-19 al 2019-09-13
Resultado obtenido entrenando desde 2019-08-19 hasta 2019-09-13
Método: EMA, Datos optimizados [1, np.int64(59)]

hit ratio: 0.8322147651006712
risk reward: 0.3301170990076825
profit factor: 1.8059347181008514
trades: 447
Resultado de sobre ajuste 0.48097588931207547
Optimizando ventana: 2019-08-26 al 2019-09-20
Resultado obtenido entrenando desde 2019-08-26 hasta 2019-09-20
Método: EMA, Datos optimizados [1, np.int64(89)]

hit ratio: 0.8389057750759878
risk reward: 0.21683293627159206
profit factor: 1.1969178082191883
trades: 329
Resultado de sobre ajuste 0.2220397275883548
Optimizando ventana: 2019-09-02 al 2019-09-27
Resultado obtenido entrenando desde 2019-09-02 hasta 2019-09-27
Método: EMA, Datos optimizados [1, np.int64(24)]

hit ratio: 0.7545008183306056
risk reward: 0.3427377426684971
profit factor: 1.1285864240726937
trades: 611
Resultado de sobre ajuste -0.3662745640636628
Optimizando ventana: 2019-09-09 al 2019-10-04
Resultado obtenido entrenando desde 2019-09-09 hasta 2019-10-04
Método: TRIMA, Datos optimizados [1, np.int64(82)]

hit ratio: 0.7649253731343284
risk reward: 0.26579069831102603
profit factor: 1.0280583613917045
trades: 268
Resultado de sobre ajuste 0.040291457487213606
Optimizando ventana: 2019-09-16 al 2019-10-11
Resultado obtenido entrenando desde 2019-09-16 hasta 2019-10-11
Método: TEMA, Datos optimizados [1, np.int64(41)]

hit ratio: 0.6788036410923277
risk reward: 0.4436010341286237
profit factor: 1.092262923656328
trades: 769
Resultado de sobre ajuste 0.1649852748885846
Optimizando ventana: 2019-09-23 al 2019-10-18
Resultado obtenido entrenando desde 2019-09-23 hasta 2019-10-18
Método: T3, Datos optimizados [1, np.int64(107)]

hit ratio: 0.7735849056603774
risk reward: 0.3070940327061931
profit factor: 1.481277098935755
trades: 212
Resultado de sobre ajuste 0.5334784177772517
Optimizando ventana: 2019-09-30 al 2019-10-25
Resultado obtenido entrenando desde 2019-09-30 hasta 2019-10-25
Método: T3, Datos optimizados [1, np.int64(102)]

hit ratio: 0.7563451776649747
risk reward: 0.42761823006087657
profit factor: 1.9307610993657758
trades: 197
Resultado de sobre ajuste 0.9097956436818523
Optimizando ventana: 2019-10-07 al 2019-11-01
Resultado obtenido entrenando desde 2019-10-07 hasta 2019-11-01
Método: WMA, Datos optimizados [1, np.int64(90)]

hit ratio: 0.7946666666666666
risk reward: 0.398692118642106
profit factor: 1.7732873336619046
trades: 375
Resultado de sobre ajuste 1.7936358488323179
Optimizando ventana: 2019-10-14 al 2019-11-08
Resultado obtenido entrenando desde 2019-10-14 hasta 2019-11-08
Método: DEMA, Datos optimizados [1, np.int64(102)]

hit ratio: 0.7632978723404256
risk reward: 0.3621927303901147
profit factor: 1.2993664202745365
trades: 376
Resultado de sobre ajuste 0.12018410769868729
Optimizando ventana: 2019-10-21 al 2019-11-15
Resultado obtenido entrenando desde 2019-10-21 hasta 2019-11-15
Método: SMA, Datos optimizados [1, np.int64(89)]

hit ratio: 0.794425087108014
risk reward: 0.2717105263157729
profit factor: 1.2147058823528671
trades: 287
Resultado de sobre ajuste -0.533371474399834
Optimizando ventana: 2019-10-28 al 2019-11-22
Resultado obtenido entrenando desde 2019-10-28 hasta 2019-11-22
Método: SMA, Datos optimizados [1, np.int64(47)]

hit ratio: 0.7777777777777778
risk reward: 0.3097369893676562
profit factor: 1.238947957470625
trades: 396
Resultado de sobre ajuste -0.042946752925670864
Optimizando ventana: 2019-11-04 al 2019-11-29
Resultado obtenido entrenando desde 2019-11-04 hasta 2019-11-29
Método: DEMA, Datos optimizados [1, np.int64(95)]

hit ratio: 0.7790973871733967
risk reward: 0.34207163371593863
profit factor: 1.304645300684045
trades: 421
Resultado de sobre ajuste -0.08225682174345648
Optimizando ventana: 2019-11-11 al 2019-12-06
Resultado obtenido entrenando desde 2019-11-11 hasta 2019-12-06
Método: MIDPOINT, Datos optimizados [1, np.int64(49)]

hit ratio: 0.7428571428571429
risk reward: 0.3788183647338817
profit factor: 1.4255533199196073
trades: 385
Resultado de sobre ajuste 0.8862243345077145
Optimizando ventana: 2019-11-18 al 2019-12-13
Resultado obtenido entrenando desde 2019-11-18 hasta 2019-12-13
Método: TRIMA, Datos optimizados [1, np.int64(105)]

hit ratio: 0.8250825082508251
risk reward: 0.3951999999999716
profit factor: 2.5999999999998127
trades: 303
Resultado de sobre ajuste 1.5006356723984893
Optimizando ventana: 2019-11-25 al 2019-12-20
Resultado obtenido entrenando desde 2019-11-25 hasta 2019-12-20
Método: MIDPOINT, Datos optimizados [1, np.int64(77)]

hit ratio: 0.8176470588235294
risk reward: 0.2751236818764202
profit factor: 1.593424657534267
trades: 340
Resultado de sobre ajuste 1.2984627612791222
Optimizando ventana: 2019-12-02 al 2019-12-27
Resultado obtenido entrenando desde 2019-12-02 hasta 2019-12-27
Método: MIDPOINT, Datos optimizados [1, np.int64(63)]

hit ratio: 0.8187134502923976
risk reward: 0.2740373883928888
profit factor: 1.4755859375001705
trades: 342
Resultado de sobre ajuste 0.7956833447106302
Optimizando ventana: 2019-12-09 al 2020-01-03
Resultado obtenido entrenando desde 2019-12-09 hasta 2020-01-03
Método: MIDPOINT, Datos optimizados [1, np.int64(67)]

hit ratio: 0.8300653594771242
risk reward: 0.23379959214321738
profit factor: 1.4846274101094301
trades: 306
Resultado de sobre ajuste 1.0322949520248241
Optimizando ventana: 2019-12-16 al 2020-01-10
Resultado obtenido entrenando desde 2019-12-16 hasta 2020-01-10
Método: TEMA, Datos optimizados [1, np.int64(4)]

hit ratio: 0.5781614559029398
risk reward: 0.7298080017161706
profit factor: 1.1960742250348348
trades: 2143
Resultado de sobre ajuste -0.057494594673180785
Optimizando ventana: 2019-12-23 al 2020-01-17
Resultado obtenido entrenando desde 2019-12-23 hasta 2020-01-17
Método: EMA, Datos optimizados [1, np.int64(71)]

hit ratio: 0.8321428571428572
risk reward: 0.27419970862702253
profit factor: 1.4857798165138665
trades: 280
Resultado de sobre ajuste 0.6192438725879392
Optimizando ventana: 2019-12-30 al 2020-01-24
Resultado obtenido entrenando desde 2019-12-30 hasta 2020-01-24
Método: EMA, Datos optimizados [1, np.int64(98)]

hit ratio: 0.8148148148148148
risk reward: 0.23263143166952227
profit factor: 1.2185455944594024
trades: 270
Resultado de sobre ajuste -0.23727647173699834
Optimizando ventana: 2020-01-06 al 2020-01-31
Resultado obtenido entrenando desde 2020-01-06 hasta 2020-01-31
Método: KAMA, Datos optimizados [1, np.int64(110)]

hit ratio: 0.7657004830917874
risk reward: 0.2717415236651406
profit factor: 1.1043854231006354
trades: 414
Resultado de sobre ajuste 0.12739521110682145
Optimizando ventana: 2020-01-13 al 2020-02-07
Resultado obtenido entrenando desde 2020-01-13 hasta 2020-02-07
Método: DEMA, Datos optimizados [1, np.int64(11)]

hit ratio: 0.6558391337973705
risk reward: 0.5112925592823175
profit factor: 1.132052455016724
trades: 1293
Resultado de sobre ajuste 0.1566384593845726
Optimizando ventana: 2020-01-20 al 2020-02-14
Resultado obtenido entrenando desde 2020-01-20 hasta 2020-02-14
Método: TRIMA, Datos optimizados [1, np.int64(107)]

hit ratio: 0.7928571428571428
risk reward: 0.22615032710351662
profit factor: 1.0914211438474064
trades: 280
Resultado de sobre ajuste 0.14373264867810068
Optimizando ventana: 2020-01-27 al 2020-02-21
Resultado obtenido entrenando desde 2020-01-27 hasta 2020-02-21
Método: TRIMA, Datos optimizados [1, np.int64(101)]

hit ratio: 0.797979797979798
risk reward: 0.23936275089711465
profit factor: 1.1345794392523236
trades: 297
Resultado de sobre ajuste -0.38106609088098675
Optimizando ventana: 2020-02-03 al 2020-02-28
Resultado obtenido entrenando desde 2020-02-03 hasta 2020-02-28
Método: WMA, Datos optimizados [1, np.int64(75)]

hit ratio: 0.7712082262210797
risk reward: 0.2803300865800898
profit factor: 1.0781926406926532
trades: 389
Resultado de sobre ajuste 0.17265663479969462
Optimizando ventana: 2020-02-10 al 2020-03-06
Resultado obtenido entrenando desde 2020-02-10 hasta 2020-03-06
Método: TRIMA, Datos optimizados [1, np.int64(96)]

hit ratio: 0.8091872791519434
risk reward: 0.358781396806198
profit factor: 1.7481051035876456
trades: 283
Resultado de sobre ajuste 0.4215294706034439
Optimizando ventana: 2020-02-17 al 2020-03-13
Resultado obtenido entrenando desde 2020-02-17 hasta 2020-03-13
Método: KAMA, Datos optimizados [1, np.int64(78)]

hit ratio: 0.782608695652174
risk reward: 0.3415856147476207
profit factor: 1.3583986074847243
trades: 437
Resultado de sobre ajuste 0.6242398307067965
Optimizando ventana: 2020-02-24 al 2020-03-20
Resultado obtenido entrenando desde 2020-02-24 hasta 2020-03-20
Método: TEMA, Datos optimizados [1, np.int64(22)]

hit ratio: 0.6644920782851818
risk reward: 0.4768984457942809
profit factor: 1.0150107219442457
trades: 1073
Resultado de sobre ajuste -0.6398771235421158
Optimizando ventana: 2020-03-02 al 2020-03-27
Resultado obtenido entrenando desde 2020-03-02 hasta 2020-03-27
Método: TRIMA, Datos optimizados [1, np.int64(59)]

hit ratio: 0.7900552486187845
risk reward: 0.2641720513453129
profit factor: 1.049350092843882
trades: 362
Resultado de sobre ajuste 0.07210570436969574
Optimizando ventana: 2020-03-09 al 2020-04-03
Resultado obtenido entrenando desde 2020-03-09 hasta 2020-04-03
Método: KAMA, Datos optimizados [1, np.int64(64)]

hit ratio: 0.7831858407079646
risk reward: 0.2454850503828273
profit factor: 0.9147548193212721
trades: 452
Resultado de sobre ajuste -0.28651826239550865
Optimizando ventana: 2020-03-16 al 2020-04-10
Resultado obtenido entrenando desde 2020-03-16 hasta 2020-04-10
Método: WMA, Datos optimizados [1, np.int64(101)]

hit ratio: 0.7625698324022346
risk reward: 0.26320111315855627
profit factor: 0.9454461038458667
trades: 358
Resultado de sobre ajuste -0.1201998043286868
Optimizando ventana: 2020-03-23 al 2020-04-17
Resultado obtenido entrenando desde 2020-03-23 hasta 2020-04-17